#############################################################################
# Makefile for building: AlgorithmeGenetic
# Generated by qmake (3.1) (Qt 5.12.4)
# Project:  AlgorithmeGentique.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile AlgorithmeGentique.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = AlgorithmeGenetic1.0.0
DISTDIR = /home/nicolas/Projet/L3/projetAlgoGenetique/Fusion/AlgorithmeGenetique/.tmp/AlgorithmeGenetic1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		OP/mainwindow.cpp \
		OP/modelisationprblm.cpp \
		OP/gene.cpp \
		OP/individu.cpp \
		OP/calculator.cpp \
		OP/button.cpp \
		OP/notebad.cpp \
		OP/entreessorties.cpp \
		OP/evaluation.cpp \
		OP/operationsgenetiques.cpp \
		OP/mythread.cpp \
		Queen/BoxEchiquier.cpp \
		Queen/bouton.cpp \
		Queen/Echiquier.cpp \
		Queen/InterfaceQueen.cpp \
		Queen/Piece.cpp \
		Queen/ProblemeDesHuitDames.cpp \
		mainwindow1.cpp \
		Interface.cpp \
		VoyageurDeCommerce/edge.cpp \
		VoyageurDeCommerce/graphwidget.cpp \
		VoyageurDeCommerce/node.cpp \
		VoyageurDeCommerce/interfaceVoyageur.cpp qrc_Ressource1.cpp \
		moc_mainwindow.cpp \
		moc_modelisationprblm.cpp \
		moc_calculator.cpp \
		moc_button.cpp \
		moc_notebad.cpp \
		moc_mythread.cpp \
		moc_bouton.cpp \
		moc_InterfaceQueen.cpp \
		moc_mainwindow1.cpp \
		moc_graphwidget.cpp \
		moc_interfaceVoyageur.cpp
OBJECTS       = main.o \
		mainwindow.o \
		modelisationprblm.o \
		gene.o \
		individu.o \
		calculator.o \
		button.o \
		notebad.o \
		entreessorties.o \
		evaluation.o \
		operationsgenetiques.o \
		mythread.o \
		BoxEchiquier.o \
		bouton.o \
		Echiquier.o \
		InterfaceQueen.o \
		Piece.o \
		ProblemeDesHuitDames.o \
		mainwindow1.o \
		Interface.o \
		edge.o \
		graphwidget.o \
		node.o \
		interfaceVoyageur.o \
		qrc_Ressource1.o \
		moc_mainwindow.o \
		moc_modelisationprblm.o \
		moc_calculator.o \
		moc_button.o \
		moc_notebad.o \
		moc_mythread.o \
		moc_bouton.o \
		moc_InterfaceQueen.o \
		moc_mainwindow1.o \
		moc_graphwidget.o \
		moc_interfaceVoyageur.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		AlgorithmeGentique.pro OP/mainwindow.h \
		OP/modelisationprblm.h \
		OP/gene.h \
		OP/individu.h \
		OP/calculator.h \
		OP/button.h \
		OP/notebad.h \
		OP/entreessorties.h \
		OP/evaluation.h \
		OP/operationsgenetiques.h \
		OP/mythread.h \
		Queen/BoxEchiquier.h \
		Queen/bouton.h \
		Queen/Echiquier.h \
		Queen/InterfaceQueen.h \
		Queen/Piece.h \
		Queen/ProblemeDesHuitDames.h \
		Interface.h \
		mainwindow1.h \
		VoyageurDeCommerce/edge.h \
		VoyageurDeCommerce/graphwidget.h \
		VoyageurDeCommerce/node.h \
		VoyageurDeCommerce/interfaceVoyageur.h main.cpp \
		OP/mainwindow.cpp \
		OP/modelisationprblm.cpp \
		OP/gene.cpp \
		OP/individu.cpp \
		OP/calculator.cpp \
		OP/button.cpp \
		OP/notebad.cpp \
		OP/entreessorties.cpp \
		OP/evaluation.cpp \
		OP/operationsgenetiques.cpp \
		OP/mythread.cpp \
		Queen/BoxEchiquier.cpp \
		Queen/bouton.cpp \
		Queen/Echiquier.cpp \
		Queen/InterfaceQueen.cpp \
		Queen/Piece.cpp \
		Queen/ProblemeDesHuitDames.cpp \
		mainwindow1.cpp \
		Interface.cpp \
		VoyageurDeCommerce/edge.cpp \
		VoyageurDeCommerce/graphwidget.cpp \
		VoyageurDeCommerce/node.cpp \
		VoyageurDeCommerce/interfaceVoyageur.cpp
QMAKE_TARGET  = AlgorithmeGenetic
DESTDIR       = 
TARGET        = AlgorithmeGenetic


first: all
####### Build rules

AlgorithmeGenetic: ui_mainwindow.h ui_modelisation.h ui_modelisationprblm.h ui_notepad.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: AlgorithmeGentique.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		AlgorithmeGentique.pro \
		Queen/Ressource1.qrc
	$(QMAKE) -o Makefile AlgorithmeGentique.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
AlgorithmeGentique.pro:
Queen/Ressource1.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile AlgorithmeGentique.pro

qmake_all: FORCE


all: Makefile AlgorithmeGenetic

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents Queen/Ressource1.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents OP/mainwindow.h OP/modelisationprblm.h OP/gene.h OP/individu.h OP/calculator.h OP/button.h OP/notebad.h OP/entreessorties.h OP/evaluation.h OP/operationsgenetiques.h OP/mythread.h Queen/BoxEchiquier.h Queen/bouton.h Queen/Echiquier.h Queen/InterfaceQueen.h Queen/Piece.h Queen/ProblemeDesHuitDames.h Interface.h mainwindow1.h VoyageurDeCommerce/edge.h VoyageurDeCommerce/graphwidget.h VoyageurDeCommerce/node.h VoyageurDeCommerce/interfaceVoyageur.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp OP/mainwindow.cpp OP/modelisationprblm.cpp OP/gene.cpp OP/individu.cpp OP/calculator.cpp OP/button.cpp OP/notebad.cpp OP/entreessorties.cpp OP/evaluation.cpp OP/operationsgenetiques.cpp OP/mythread.cpp Queen/BoxEchiquier.cpp Queen/bouton.cpp Queen/Echiquier.cpp Queen/InterfaceQueen.cpp Queen/Piece.cpp Queen/ProblemeDesHuitDames.cpp mainwindow1.cpp Interface.cpp VoyageurDeCommerce/edge.cpp VoyageurDeCommerce/graphwidget.cpp VoyageurDeCommerce/node.cpp VoyageurDeCommerce/interfaceVoyageur.cpp $(DISTDIR)/
	$(COPY_FILE) --parents OP/mainwindow.ui OP/modelisation.ui OP/modelisationprblm.ui OP/notepad.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_Ressource1.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_Ressource1.cpp
qrc_Ressource1.cpp: Queen/Ressource1.qrc \
		/usr/lib/qt5/bin/rcc \
		Queen/Manuel.pdf \
		Queen/queen.png
	/usr/lib/qt5/bin/rcc -name Ressource1 Queen/Ressource1.qrc -o qrc_Ressource1.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_modelisationprblm.cpp moc_calculator.cpp moc_button.cpp moc_notebad.cpp moc_mythread.cpp moc_bouton.cpp moc_InterfaceQueen.cpp moc_mainwindow1.cpp moc_graphwidget.cpp moc_interfaceVoyageur.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_modelisationprblm.cpp moc_calculator.cpp moc_button.cpp moc_notebad.cpp moc_mythread.cpp moc_bouton.cpp moc_InterfaceQueen.cpp moc_mainwindow1.cpp moc_graphwidget.cpp moc_interfaceVoyageur.cpp
moc_mainwindow.cpp: OP/mainwindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/nicolas/Projet/L3/projetAlgoGenetique/Fusion/AlgorithmeGenetique/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/nicolas/Projet/L3/projetAlgoGenetique/Fusion/AlgorithmeGenetique -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include OP/mainwindow.h -o moc_mainwindow.cpp

moc_modelisationprblm.cpp: OP/modelisationprblm.h \
		OP/mythread.h \
		OP/individu.h \
		OP/gene.h \
		OP/evaluation.h \
		OP/entreessorties.h \
		OP/operationsgenetiques.h \
		OP/notebad.h \
		OP/calculator.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/nicolas/Projet/L3/projetAlgoGenetique/Fusion/AlgorithmeGenetique/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/nicolas/Projet/L3/projetAlgoGenetique/Fusion/AlgorithmeGenetique -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include OP/modelisationprblm.h -o moc_modelisationprblm.cpp

moc_calculator.cpp: OP/calculator.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/nicolas/Projet/L3/projetAlgoGenetique/Fusion/AlgorithmeGenetique/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/nicolas/Projet/L3/projetAlgoGenetique/Fusion/AlgorithmeGenetique -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include OP/calculator.h -o moc_calculator.cpp

moc_button.cpp: OP/button.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/nicolas/Projet/L3/projetAlgoGenetique/Fusion/AlgorithmeGenetique/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/nicolas/Projet/L3/projetAlgoGenetique/Fusion/AlgorithmeGenetique -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include OP/button.h -o moc_button.cpp

moc_notebad.cpp: OP/notebad.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/nicolas/Projet/L3/projetAlgoGenetique/Fusion/AlgorithmeGenetique/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/nicolas/Projet/L3/projetAlgoGenetique/Fusion/AlgorithmeGenetique -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include OP/notebad.h -o moc_notebad.cpp

moc_mythread.cpp: OP/mythread.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/nicolas/Projet/L3/projetAlgoGenetique/Fusion/AlgorithmeGenetique/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/nicolas/Projet/L3/projetAlgoGenetique/Fusion/AlgorithmeGenetique -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include OP/mythread.h -o moc_mythread.cpp

moc_bouton.cpp: Queen/bouton.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/nicolas/Projet/L3/projetAlgoGenetique/Fusion/AlgorithmeGenetique/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/nicolas/Projet/L3/projetAlgoGenetique/Fusion/AlgorithmeGenetique -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Queen/bouton.h -o moc_bouton.cpp

moc_InterfaceQueen.cpp: Queen/InterfaceQueen.h \
		OP/operationsgenetiques.h \
		OP/evaluation.h \
		OP/individu.h \
		OP/gene.h \
		Queen/ProblemeDesHuitDames.h \
		Queen/Echiquier.h \
		Queen/Piece.h \
		Queen/BoxEchiquier.h \
		Queen/bouton.h \
		OP/mythread.h \
		OP/entreessorties.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/nicolas/Projet/L3/projetAlgoGenetique/Fusion/AlgorithmeGenetique/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/nicolas/Projet/L3/projetAlgoGenetique/Fusion/AlgorithmeGenetique -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Queen/InterfaceQueen.h -o moc_InterfaceQueen.cpp

moc_mainwindow1.cpp: mainwindow1.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/nicolas/Projet/L3/projetAlgoGenetique/Fusion/AlgorithmeGenetique/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/nicolas/Projet/L3/projetAlgoGenetique/Fusion/AlgorithmeGenetique -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow1.h -o moc_mainwindow1.cpp

moc_graphwidget.cpp: VoyageurDeCommerce/graphwidget.h \
		VoyageurDeCommerce/edge.h \
		OP/operationsgenetiques.h \
		OP/evaluation.h \
		OP/individu.h \
		OP/gene.h \
		OP/entreessorties.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/nicolas/Projet/L3/projetAlgoGenetique/Fusion/AlgorithmeGenetique/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/nicolas/Projet/L3/projetAlgoGenetique/Fusion/AlgorithmeGenetique -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include VoyageurDeCommerce/graphwidget.h -o moc_graphwidget.cpp

moc_interfaceVoyageur.cpp: VoyageurDeCommerce/interfaceVoyageur.h \
		VoyageurDeCommerce/graphwidget.h \
		VoyageurDeCommerce/edge.h \
		OP/operationsgenetiques.h \
		OP/evaluation.h \
		OP/individu.h \
		OP/gene.h \
		OP/entreessorties.h \
		mainwindow1.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/nicolas/Projet/L3/projetAlgoGenetique/Fusion/AlgorithmeGenetique/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/nicolas/Projet/L3/projetAlgoGenetique/Fusion/AlgorithmeGenetique -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include VoyageurDeCommerce/interfaceVoyageur.h -o moc_interfaceVoyageur.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_modelisation.h ui_modelisationprblm.h ui_notepad.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_modelisation.h ui_modelisationprblm.h ui_notepad.h
ui_mainwindow.h: OP/mainwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic OP/mainwindow.ui -o ui_mainwindow.h

ui_modelisation.h: OP/modelisation.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic OP/modelisation.ui -o ui_modelisation.h

ui_modelisationprblm.h: OP/modelisationprblm.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic OP/modelisationprblm.ui -o ui_modelisationprblm.h

ui_notepad.h: OP/notepad.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic OP/notepad.ui -o ui_notepad.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp Queen/InterfaceQueen.h \
		OP/operationsgenetiques.h \
		OP/evaluation.h \
		OP/individu.h \
		OP/gene.h \
		Queen/ProblemeDesHuitDames.h \
		Queen/Echiquier.h \
		Queen/Piece.h \
		Queen/BoxEchiquier.h \
		Queen/bouton.h \
		OP/mythread.h \
		OP/entreessorties.h \
		mainwindow1.h \
		OP/modelisationprblm.h \
		OP/notebad.h \
		OP/calculator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: OP/mainwindow.cpp OP/mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o OP/mainwindow.cpp

modelisationprblm.o: OP/modelisationprblm.cpp OP/modelisationprblm.h \
		OP/mythread.h \
		OP/individu.h \
		OP/gene.h \
		OP/evaluation.h \
		OP/entreessorties.h \
		OP/operationsgenetiques.h \
		OP/notebad.h \
		OP/calculator.h \
		ui_modelisationprblm.h \
		mainwindow1.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modelisationprblm.o OP/modelisationprblm.cpp

gene.o: OP/gene.cpp OP/gene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gene.o OP/gene.cpp

individu.o: OP/individu.cpp OP/individu.h \
		OP/gene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o individu.o OP/individu.cpp

calculator.o: OP/calculator.cpp OP/button.h \
		OP/calculator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calculator.o OP/calculator.cpp

button.o: OP/button.cpp OP/button.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o button.o OP/button.cpp

notebad.o: OP/notebad.cpp OP/notebad.h \
		ui_notepad.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o notebad.o OP/notebad.cpp

entreessorties.o: OP/entreessorties.cpp OP/entreessorties.h \
		OP/individu.h \
		OP/gene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o entreessorties.o OP/entreessorties.cpp

evaluation.o: OP/evaluation.cpp OP/evaluation.h \
		OP/individu.h \
		OP/gene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o evaluation.o OP/evaluation.cpp

operationsgenetiques.o: OP/operationsgenetiques.cpp OP/operationsgenetiques.h \
		OP/evaluation.h \
		OP/individu.h \
		OP/gene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o operationsgenetiques.o OP/operationsgenetiques.cpp

mythread.o: OP/mythread.cpp OP/mythread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mythread.o OP/mythread.cpp

BoxEchiquier.o: Queen/BoxEchiquier.cpp Queen/BoxEchiquier.h \
		Queen/Piece.h \
		Queen/InterfaceQueen.h \
		OP/operationsgenetiques.h \
		OP/evaluation.h \
		OP/individu.h \
		OP/gene.h \
		Queen/ProblemeDesHuitDames.h \
		Queen/Echiquier.h \
		Queen/bouton.h \
		OP/mythread.h \
		OP/entreessorties.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BoxEchiquier.o Queen/BoxEchiquier.cpp

bouton.o: Queen/bouton.cpp Queen/bouton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bouton.o Queen/bouton.cpp

Echiquier.o: Queen/Echiquier.cpp Queen/Echiquier.h \
		Queen/Piece.h \
		Queen/BoxEchiquier.h \
		Queen/InterfaceQueen.h \
		OP/operationsgenetiques.h \
		OP/evaluation.h \
		OP/individu.h \
		OP/gene.h \
		Queen/ProblemeDesHuitDames.h \
		Queen/bouton.h \
		OP/mythread.h \
		OP/entreessorties.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Echiquier.o Queen/Echiquier.cpp

InterfaceQueen.o: Queen/InterfaceQueen.cpp Queen/InterfaceQueen.h \
		OP/operationsgenetiques.h \
		OP/evaluation.h \
		OP/individu.h \
		OP/gene.h \
		Queen/ProblemeDesHuitDames.h \
		Queen/Echiquier.h \
		Queen/Piece.h \
		Queen/BoxEchiquier.h \
		Queen/bouton.h \
		OP/mythread.h \
		OP/entreessorties.h \
		mainwindow1.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InterfaceQueen.o Queen/InterfaceQueen.cpp

Piece.o: Queen/Piece.cpp Queen/Piece.h \
		Queen/BoxEchiquier.h \
		Queen/InterfaceQueen.h \
		OP/operationsgenetiques.h \
		OP/evaluation.h \
		OP/individu.h \
		OP/gene.h \
		Queen/ProblemeDesHuitDames.h \
		Queen/Echiquier.h \
		Queen/bouton.h \
		OP/mythread.h \
		OP/entreessorties.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Piece.o Queen/Piece.cpp

ProblemeDesHuitDames.o: Queen/ProblemeDesHuitDames.cpp Queen/ProblemeDesHuitDames.h \
		OP/individu.h \
		OP/gene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ProblemeDesHuitDames.o Queen/ProblemeDesHuitDames.cpp

mainwindow1.o: mainwindow1.cpp Interface.h \
		mainwindow1.h \
		OP/modelisationprblm.h \
		OP/mythread.h \
		OP/individu.h \
		OP/gene.h \
		OP/evaluation.h \
		OP/entreessorties.h \
		OP/operationsgenetiques.h \
		OP/notebad.h \
		OP/calculator.h \
		Queen/InterfaceQueen.h \
		Queen/ProblemeDesHuitDames.h \
		Queen/Echiquier.h \
		Queen/Piece.h \
		Queen/BoxEchiquier.h \
		Queen/bouton.h \
		VoyageurDeCommerce/interfaceVoyageur.h \
		VoyageurDeCommerce/graphwidget.h \
		VoyageurDeCommerce/edge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow1.o mainwindow1.cpp

Interface.o: Interface.cpp Interface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Interface.o Interface.cpp

edge.o: VoyageurDeCommerce/edge.cpp VoyageurDeCommerce/edge.h \
		VoyageurDeCommerce/node.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o edge.o VoyageurDeCommerce/edge.cpp

graphwidget.o: VoyageurDeCommerce/graphwidget.cpp VoyageurDeCommerce/graphwidget.h \
		VoyageurDeCommerce/edge.h \
		OP/operationsgenetiques.h \
		OP/evaluation.h \
		OP/individu.h \
		OP/gene.h \
		OP/entreessorties.h \
		VoyageurDeCommerce/node.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphwidget.o VoyageurDeCommerce/graphwidget.cpp

node.o: VoyageurDeCommerce/node.cpp VoyageurDeCommerce/edge.h \
		VoyageurDeCommerce/node.h \
		VoyageurDeCommerce/graphwidget.h \
		OP/operationsgenetiques.h \
		OP/evaluation.h \
		OP/individu.h \
		OP/gene.h \
		OP/entreessorties.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o node.o VoyageurDeCommerce/node.cpp

interfaceVoyageur.o: VoyageurDeCommerce/interfaceVoyageur.cpp VoyageurDeCommerce/interfaceVoyageur.h \
		VoyageurDeCommerce/graphwidget.h \
		VoyageurDeCommerce/edge.h \
		OP/operationsgenetiques.h \
		OP/evaluation.h \
		OP/individu.h \
		OP/gene.h \
		OP/entreessorties.h \
		mainwindow1.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o interfaceVoyageur.o VoyageurDeCommerce/interfaceVoyageur.cpp

qrc_Ressource1.o: qrc_Ressource1.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Ressource1.o qrc_Ressource1.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_modelisationprblm.o: moc_modelisationprblm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_modelisationprblm.o moc_modelisationprblm.cpp

moc_calculator.o: moc_calculator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_calculator.o moc_calculator.cpp

moc_button.o: moc_button.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_button.o moc_button.cpp

moc_notebad.o: moc_notebad.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_notebad.o moc_notebad.cpp

moc_mythread.o: moc_mythread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mythread.o moc_mythread.cpp

moc_bouton.o: moc_bouton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bouton.o moc_bouton.cpp

moc_InterfaceQueen.o: moc_InterfaceQueen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_InterfaceQueen.o moc_InterfaceQueen.cpp

moc_mainwindow1.o: moc_mainwindow1.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow1.o moc_mainwindow1.cpp

moc_graphwidget.o: moc_graphwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphwidget.o moc_graphwidget.cpp

moc_interfaceVoyageur.o: moc_interfaceVoyageur.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_interfaceVoyageur.o moc_interfaceVoyageur.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/AlgorithmeGenetic/bin || mkdir -p $(INSTALL_ROOT)/opt/AlgorithmeGenetic/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/AlgorithmeGenetic/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/AlgorithmeGenetic/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/AlgorithmeGenetic/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/AlgorithmeGenetic/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

