######################################################################
# Automatically generated by qmake (3.1) Tue May 19 18:15:19 2020
######################################################################

TEMPLATE = app
TARGET = GRAVOY
INCLUDEPATH += .

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += edge.h \
           EntreesSorties.h \
           evaluation.h \
           gene.h \
           graphwidget.h \
           individu.h \
           node.h \
           operations_genetiques.h \
           Interface/interface.h
SOURCES += edge.cpp \
           EntreesSorties.cpp \
           evaluation.cpp \
           gene.cpp \
           graphwidget.cpp \
           individu.cpp \
           node.cpp \
           operations_genetiques.cpp \
           Interface/interface.cpp \
           Interface/main.cpp

QT += widgets
QT += core